[package]
name = "sov-vec-setter"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A Sovereign SDK example module for setting/reading vectors from state"

version = { workspace = true }
publish = false
readme = "README.md"
resolver = "2"

[dev-dependencies]
sov-modules-api = { path = "../../../sov-modules-api", features = ["native", "macros"] }
sov-prover-storage-manager = { path = "../../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }
tempfile = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
clap = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
sov-modules-api = { path = "../../../sov-modules-api", default-features = false, features = ["macros"] }
sov-state = { path = "../../../sov-state", default-features = false }
thiserror = { workspace = true }

[features]
default = ["native"]
native = ["serde_json", "jsonrpsee", "schemars", "clap", "sov-modules-api/native"]
