{
 "title": "Import From Prod New Full Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current L1 and L2 Block",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fullnode_current_l2_block", "legendFormat": "Current L2 Block" },
    { "expr": "fullnode_current_l1_block", "legendFormat": "Current L1 Block" }
   ]
  },
  {
   "title": "Highest Committed Index, L2 Height, Proven L2 Height",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fullnode_highest_committed_index",
     "legendFormat": "Highest Committed Index"
    },
    {
     "expr": "fullnode_highest_committed_l2_height",
     "legendFormat": "Highest Committed L2 Height"
    },
    {
     "expr": "fullnode_highest_proven_l2_height",
     "legendFormat": "Highest Proven L2 Height"
    }
   ]
  },
  {
   "title": "Per-second average rate of RPC requests over the last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(rpc_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scan L1 Block Time By L1 Height",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "fullnode_current_l1_block", "legendFormat": "__auto" },
    {
     "expr": "fullnode_scan_l1_block_duration_secs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rpc Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rpc_response_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process L2 Block Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "fullnode_process_l2_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "L2 Block Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "fullnode_l2_block_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batch Proof Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "fullnode_batch_proof_processing_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commitment Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "fullnode_sequencer_commitment_processing_time",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}