{
 "title": "New Light Client Prover Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current L1 Block",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "light_client_prover_current_l1_block",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proving Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "light_client_prover_proving_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scan L1 Block Duration",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "light_client_prover_current_l1_block",
     "legendFormat": "__auto"
    },
    {
     "expr": "light_client_prover_scan_l1_block_duration_secs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cycle Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "proving_session_cycle_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Proven L2 height and commitment index",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "light_client_prover_highest_proven_index",
     "legendFormat": "Commitment index"
    },
    {
     "expr": "light_client_prover_highest_proven_l2_height",
     "legendFormat": "L2 height"
    }
   ]
  },
  {
   "title": "Rpc Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "light_client_prover_rpc_response_time",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}