[package]
name = "recovered-pubkey-provider"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
publish = false
resolver = "2"

[dependencies]
parking_lot = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
native = [
  "dep:parking_lot",
]
