//! Helps initialize authority addresses that require environment variables at compile time.

use std::path::PathBuf;
use std::{env, fs};

fn normalize_addr(mut s: String, default: &str) -> String {
    if s.is_empty() {
        s = default.to_string();
    }
    if !s.starts_with("0x") {
        s = format!("0x{s}");
    }
    // very basic validation
    assert!(
        s.len() == 42,
        "address must be 20 bytes hex (42 chars with 0x): {s}"
    );
    s
}

fn main() {
    // re-run build if these change
    for i in 1..=5 {
        println!("cargo:rerun-if-env-changed=METHOD_ID_UPGRADE_AUTHORITY_DA_ADDRESS_{i}");
    }

    let defaults = [
        "0xd51bd554b82aa486f56030bef90b70a27a4f6d20",
        "0xfef24931c137d6c0df4f76116e0e58d281203360",
        "0xbb3833932330eef589dd56e855f2ca1ac015d200",
        "0xe976fdbc72670c34b7973ae3fa7d38478eade018",
        "0x8632ebc44c4515c9b85fae29eae3fd3722fd35ea",
    ];

    let mut addrs = Vec::new();
    for (idx, def) in defaults.iter().enumerate() {
        let k = format!("METHOD_ID_UPGRADE_AUTHORITY_DA_ADDRESS_{}", idx + 1);
        let v = env::var(&k).unwrap_or_default();
        addrs.push(normalize_addr(v, def));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.clone().join("authority_addrs.rs");

    let body = format!(
        r#"
// @generated by build.rs
use alloy_primitives::{{Address, address}};

pub const NIGHTLY_METHOD_ID_UPGRADE_AUTHORITY_DA_ADDRESSES: [Address; {addrs_len}] = [
    address!("{a0}"),
    address!("{a1}"),
    address!("{a2}"),
    address!("{a3}"),
    address!("{a4}"),
];

pub const TEST_NETWORK_WITH_FORKS_METHOD_ID_UPGRADE_AUTHORITY_DA_ADDRESSES: [Address; {addrs_len}] = [
    address!("{a0}"),
    address!("{a1}"),
    address!("{a2}"),
    address!("{a3}"),
    address!("{a4}"),
];
"#,
        addrs_len = addrs.len(),
        a0 = addrs[0],
        a1 = addrs[1],
        a2 = addrs[2],
        a3 = addrs[3],
        a4 = addrs[4],
    );

    fs::write(dest, body).unwrap();
}
