[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Following options strips the metadata from contracts, this is done to ensure a more stable compilation
bytecode_hash = "none"
cbor_metadata = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
