[package]
name = "sov-accessory-state"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = false
resolver = "2"

[dependencies]
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
sov-modules-api = { path = "../../../sov-modules-api" }
sov-state = { path = "../../../sov-state" }
serde = { workspace = true, optional = true }
borsh = { workspace = true, features = ["rc"] }

[dev-dependencies]
tempfile = { workspace = true }
sov-prover-storage-manager = { path = "../../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }

[features]
default = []
native = ["serde", "sov-modules-api/native", "dep:jsonrpsee"]
