[package]
name = "sov-nft-module"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = "sovereign.xyz"
license = { workspace = true }
publish = false
description = "A Sovereign SDK module for managing non-fungible tokens"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }

sov-modules-api = { path = "../../sov-modules-api" }
sov-modules-macros = { path = "../../sov-modules-macros" }
sov-state = { path = "../../sov-state" }

postgres = { version = "0.19.7", optional = true }
tokio = { version = "1.35.0", features = ["full"], optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
sov-data-generators = { path = "../../utils/sov-data-generators" }
sov-nft-module = { version = "*", features = ["native"], path = "." }
sov-prover-storage-manager = { path = "../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }
tempfile = { workspace = true }

[features]
default = []
offchain = ["postgres", "tokio", "tracing"]
native = [
  "serde",
  "serde_json",
  "jsonrpsee",
  "schemars",
  "sov-state/native",
  "sov-modules-api/native",
]
serde = []
test = ["native"]
