[package]
name = "sov-data-generators"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A set of generator utils used to automatically produce and serialize transaction data"

version = { workspace = true }
publish = false
resolver = "2"

[dependencies]
sov-bank = { path = "../../module-implementations/sov-bank", features = ["native"] }
sov-mock-da = { path = "../../../adapters/mock-da", features = ["native"] }
sov-modules-api = { path = "../../sov-modules-api", features = ["native"] }
sov-modules-stf-blueprint = { path = "../../sov-modules-stf-blueprint", features = ["native"] }
sov-state = { path = "../../sov-state" }
sov-value-setter = { path = "../../module-implementations/examples/sov-value-setter", features = ["native"] }

borsh = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
