[public_keys]
sequencer_public_key = "204040e364c10f2bec9c1fe500a1cd4c247c89d650a01ed7e82caba867877c21"
sequencer_da_pub_key = "02588d202afcc1ee4ab5254c7847ec25b9a135bbda0f2bc69ee1a714749fd77dc9"
prover_da_pub_key = ""

[da]
# fill here
node_url = ""
# fill here
node_username = ""
# fill here
node_password = ""
network = "regtest"
tx_backup_dir = ""
da_private_key = "E9873D79C6D87DC0FB6A5778633389F4453213303DA61F20BD67FC233AA33262"

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "resources/dbs/full-node-db"

[rpc]
# the host and port to bind the rpc server for
bind_host = "127.0.0.1"
bind_port = 12346
enable_subscriptions = true
max_subscriptions_per_connection = 100

[runner]
sequencer_client_url = "http://0.0.0.0:12345"
include_tx_body = false
