[package]
name = "sov-mock-da"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
readme = "README.md"
repository.workspace = true
description = "Mock implementation of Data Availability layer for testing purposes"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
borsh = { workspace = true, features = ["bytes"] }
bytes = { workspace = true, features = ["serde"] }
futures = { workspace = true, optional = true }
hex = { workspace = true }
lazy_static = { version = "1.4.0", optional = true }
pin-project = { workspace = true, optional = true }
rusqlite = { version = "0.31.0", features = ["bundled"], optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true }
tokio = { workspace = true, optional = true }
tokio-stream = { version = "0.1.14", features = ["full"], optional = true }
tracing = { workspace = true }

sov-rollup-interface = { path = "../../rollup-interface", version = "0.3" }

[dev-dependencies]
futures = { workspace = true }
sov-mock-da = { path = ".", features = ["native"] }

[features]
default = []
native = [
  "dep:rusqlite",
  "dep:serde_json",
  "dep:tokio",
  "dep:lazy_static",
  "dep:tokio-stream",
  "dep:futures",
  "dep:pin-project",
  "sov-rollup-interface/native",
]
