[package]
name = "sov-prover-incentives"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A Sovereign SDK module for incentivizing provers"

version = { workspace = true }
readme = "README.md"
resolver = "2"

[dev-dependencies]
sov-mock-da = { path = "../../../adapters/mock-da", features = ["native"] }
sov-mock-zkvm = { path = "../../../adapters/mock-zkvm" }
sov-modules-api = { path = "../../sov-modules-api", version = "0.3", features = ["native"] }
sov-prover-incentives = { features = ["native"], path = "." }
sov-prover-storage-manager = { path = "../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }
tempfile = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }

sov-bank = { path = "../sov-bank", version = "0.3" }
sov-modules-api = { path = "../../sov-modules-api", version = "0.3" }
sov-state = { path = "../../sov-state", version = "0.3" }

[features]
default = []
native = ["serde_json", "schemars", "sov-state/native", "sov-modules-api/native"]
