[package]
name = "sov-attester-incentives"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A Sovereign SDK module for incentivizing provers"

version = { workspace = true }
publish = false
readme = "README.md"
resolver = "2"

[dev-dependencies]
sov-attester-incentives = { path = ".", features = ["native"] }
sov-mock-da = { path = "../../../adapters/mock-da", features = ["native"] }
sov-mock-zkvm = { path = "../../../adapters/mock-zkvm" }
sov-modules-api = { path = "../../sov-modules-api", version = "0.3" }
sov-modules-core = { path = "../../sov-modules-core", version = "0.3", features = ["mocks"] }
sov-prover-storage-manager = { path = "../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }
sov-rollup-interface = { path = "../../../rollup-interface", version = "0.3" }
tempfile = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
jmt = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }

sov-bank = { path = "../sov-bank", version = "0.3" }
sov-chain-state = { path = "../sov-chain-state", version = "0.3" }
sov-modules-api = { path = "../../sov-modules-api", version = "0.3" }
sov-state = { path = "../../sov-state", version = "0.3" }

[features]
default = []
native = [
  "serde_json",
  "sov-modules-api/native",
  "sov-bank/native",
  "sov-chain-state/native",
  "sov-state/native",
]
