[package]
name = "const-rollup-config"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = "sovereign.xyz"
license = { workspace = true }
publish = false
