[package]
name = "sov-rng-da-service"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
publish = false
resolver = "2"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
borsh = { workspace = true }
# Sovereign dependencies
demo-stf = { path = "../../../sovereign-sdk/examples/demo-stf", features = ["native"] }
futures = { workspace = true }
serde = { workspace = true }
sov-bank = { path = "../../module-system/module-implementations/sov-bank" }
sov-mock-da = { path = "../../adapters/mock-da", features = ["native"] }
sov-modules-api = { path = "../../module-system/sov-modules-api", features = ["native"] }
sov-rollup-interface = { path = "../../rollup-interface", features = ["native"] }
tokio = { workspace = true }

hex = { workspace = true }
