[package]
name = "sov-sequencer-registry"
description = "A Sovereign SDK module for registering rollup sequencers"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"

resolver = "2"

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
sov-bank = { path = "../sov-bank", version = "0.3" }
sov-modules-api = { path = "../../sov-modules-api", version = "0.3" }
sov-state = { path = "../../sov-state", version = "0.3" }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
borsh = { workspace = true, features = ["rc"] }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
sov-zk-cycle-macros = { path = "../../../utils/zk-cycle-macros", version = "0.3", optional = true }
risc0-zkvm = { workspace = true, default-features = false, features = ["std"], optional = true }
risc0-zkvm-platform = { workspace = true, optional = true }
sov-zk-cycle-utils = { path = "../../../utils/zk-cycle-utils", version = "0.3", optional = true }

[dev-dependencies]
tempfile = { workspace = true }
sov-sequencer-registry = { path = ".", features = ["native"] }
sov-mock-da = { path = "../../../adapters/mock-da", features = ["native"] }
sov-prover-storage-manager = { path = "../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }

[features]
bench = ["sov-zk-cycle-macros/bench", "risc0-zkvm", "risc0-zkvm-platform", "sov-zk-cycle-utils"]
default = []
arbitrary = ["dep:arbitrary", "dep:proptest", "dep:proptest-derive"]
native = [
    "serde",
    "serde_json",
    "jsonrpsee",
    "schemars",
    "clap",
    "sov-state/native",
    "sov-modules-api/native",
    # This:
    "sov-bank/native",
]
serde = []
