[package]
name = "demo-simple-stf"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = "sovereign.xyz"
license = { workspace = true }
publish = false
resolver = "2"

[dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }

sov-rollup-interface = { path = "../../rollup-interface" }

[dev-dependencies]
sov-mock-da = { path = "../../adapters/mock-da" }
sov-mock-zkvm = { path = "../../adapters/mock-zkvm" }
