[public_keys]
sequencer_public_key = "52f41a5076498d1ae8bdfa57d19e91e3c2c94b6de21985d099cd48cfa7aef174"
sequencer_da_pub_key = "039cd55f9b3dcf306c4d54f66cd7c4b27cc788632cd6fb73d80c99d303c6536486"
prover_da_pub_key = "03fc6fb2ef68368009c895d2d4351dcca4109ec2f5f327291a0553570ce769f5e5"

[da]
# can change this
node_url = ""
# fill here
node_username = ""
# fill here                                       
node_password = ""
network = "signet"

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "full-node-db"

[rpc]
# the host and port to bind the rpc server for
bind_host = "0.0.0.0"
bind_port = 12346

[runner]
sequencer_client_url = "https://rpc.devnet.citrea.xyz"
# set this to true if you want to include soft confirmation tx bodies
include_tx_body = false
