[package]
name = "sov-value-setter"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A Sovereign SDK example module for setting/reading value from state"

version = { workspace = true }
publish = false
readme = "README.md"
resolver = "2"

[dev-dependencies]
sov-modules-api = { path = "../../../sov-modules-api", features = ["native"] }
sov-prover-storage-manager = { path = "../../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }
sov-value-setter = { path = ".", features = ["native"] }
tempfile = { workspace = true }

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
clap = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
sov-modules-api = { path = "../../../sov-modules-api" }
sov-state = { path = "../../../sov-state" }
thiserror = { workspace = true }

[features]
default = []
native = ["serde", "serde_json", "jsonrpsee", "schemars", "clap", "sov-modules-api/native", "sov-state/native"]
serde = []
