[package]
name = "citrea-primitives"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
# Sov SDK deps
sov-rollup-interface = { path = "../sovereign-sdk/rollup-interface" }
serde = { workspace = true, features = ["derive"] }

# R0
risc0-zkvm = { workspace = true, default-features = false, optional = true }

# 3rd-party deps
alloy-eips = { workspace = true }
brotli = { workspace = true }

[features]
testing = ["sov-rollup-interface/testing"]
r0 = ["dep:risc0-zkvm"]
