[package]
name = "da_client"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = "0.28.0"
anchor-lang = "0.28.0"
anyhow = "1.0.75"
backoff = { version = "0.4.0", features = ["tokio"] }
blake3 = "1.3.3"
blockroot = { path = "../solana_da_programs/programs/blockroot", features = ["no-entrypoint"] }
bs58 = "0.5.0"
clap = { workspace = true }
env_logger = "0.10.0"
futures = "0.3.24"
hex = "0.4.3"
log = { version = "0.4.14", features = ["std"] }
rand = "0.8.5"
solana-rpc-client = "1.16"
solana-runtime = "1.16"
solana-sdk = "1.16"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros", "time"] }
yellowstone-grpc-client = { git = "https://github.com/rpcpool/yellowstone-grpc.git", package = "yellowstone-grpc-client", rev = "v1.9.0+solana.1.16.15" }
yellowstone-grpc-proto = { git = "https://github.com/rpcpool/yellowstone-grpc.git", package = "yellowstone-grpc-proto", rev = "v1.9.0+solana.1.16.15" }

[workspace]
