[package]
name = "sov-soft-confirmations-kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }

sov-blob-storage = { path = "../module-implementations/sov-blob-storage" }
sov-chain-state = { path = "../module-implementations/sov-chain-state" }
sov-modules-api = { path = "../sov-modules-api", version = "0.3" }
sov-state = { path = "../sov-state", version = "0.3" }

[features]
default = []
native = [
  "sov-state/native",
  "sov-modules-api/native",
  "sov-chain-state/native",
  "sov-blob-storage/native",
]
