[package]
name = "sov-bank"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A Sovereign SDK managing fungible tokens"

version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
clap = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }

sov-modules-api = { path = "../../sov-modules-api", default-features = false }
sov-state = { path = "../../sov-state" }

[dev-dependencies]
sov-bank = { path = ".", features = ["native", "test-utils"] }
sov-prover-storage-manager = { path = "../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }
tempfile = { workspace = true }

[features]
default = []
native = [
  "serde",
  "serde_json",
  "jsonrpsee",
  "clap",
  "schemars",
  "sov-state/native",
  "sov-modules-api/native",
]
cli = ["native"]
serde = []
test-utils = []
