[package]
name = "sequencer-client"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = false
resolver = "2"

[dependencies]
sov-rollup-interface = { path = "../../rollup-interface" }

anyhow = { workspace = true }
tracing = { workspace = true }
jsonrpsee = { workspace = true, features = ["http-client"] }

serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }

ethers = { workspace = true }
tokio = { workspace = true }

reth-rpc-types = { workspace = true }
reth-primitives = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }


[features]
default = []
local = []
native = ["sov-rollup-interface/native"]
