name: 'Install risc0'
description: 'Installs risc0 toolchain'

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache risc0 toolchain
      id: cache-risc0
      uses: ubicloud/cache@v4
      with:
        path: ~/.risc0
        key: risc0-${{ runner.os }}-cargo-risczero-3.0.3-r0vm-3.0.3-rust-1.88.0

    - name: Install risc0
      if: steps.cache-risc0.outputs.cache-hit != 'true'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        curl -L https://risczero.com/install | bash
        export PATH="$PATH:$HOME/.risc0/bin"
        rzup install cargo-risczero 3.0.3
        rzup install cpp
        rzup install r0vm 3.0.3
        rzup install rust 1.88.0

    - name: Add risc0 to PATH
      shell: bash
      run: echo "$HOME/.risc0/bin" >> $GITHUB_PATH
