[package]
name = "citrea-sp1-host"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
publish = false
readme = "README.md"
resolver = "2"

[dependencies]
citrea-sp1-guest = { path = "../guest", features = ["native"]}
anyhow = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
sov-db = { path = "../../sovereign-sdk/full-node/db/sov-db" }
sov-rollup-interface = { path = "../../sovereign-sdk/rollup-interface", default-features = false }
sp1-sdk = { workspace = true, default-features = false, features = ["network"] }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
sp1-build.workspace = true

[features]
cuda = ["sp1-sdk/cuda"]
