[da]
celestia_rpc_auth_token = "<RPC_TOKEN>"
celestia_rpc_address = "<ADDRESS>"
max_celestia_response_body_size = 104_857_600
celestia_rpc_timeout_seconds = 60

[storage]
path = "<STORAGE_PATH>"

[runner]
start_height = 3

[runner.rpc_config]
bind_host = "127.0.0.1"
bind_port = 12345
