[package]
name = "sov-modules-api"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Defines the interface of the Sovereign SDK module system"

version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
bech32 = { workspace = true }
borsh = { workspace = true }
clap = { workspace = true, optional = true }
derive_more = { workspace = true, default-features = true }
hex = { workspace = true }
jmt = { workspace = true }
jsonrpsee = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
schemars = { workspace = true, optional = true, features = [] }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true }
sov-modules-core = { path = "../sov-modules-core", version = "0.3" }
sov-modules-macros = { path = "../sov-modules-macros", version = "0.3", optional = true }
sov-prover-storage-manager = { path = "../../full-node/sov-prover-storage-manager", optional = true }
sov-rollup-interface = { path = "../../rollup-interface", version = "0.3" }
sov-state = { path = "../sov-state", version = "0.3" }
thiserror = { workspace = true }

# The risc0 patch only applies to version 2.0.0 exactly.
ed25519-dalek = { version = "=2.0.0", default-features = false, features = ["serde"] }
rand = { workspace = true, optional = true }

# sov-zk-cycle-macros = { path = "../../utils/zk-cycle-macros", version = "0.3", optional = true }
risc0-zkvm = { workspace = true, default-features = false, features = ["std"], optional = true }
risc0-zkvm-platform = { workspace = true, optional = true }

[dev-dependencies]
bincode = { workspace = true }
sov-bank = { path = "../module-implementations/sov-bank", features = ["native"] }
sov-db = { path = "../../full-node/db/sov-db" }
sov-mock-da = { path = "../../adapters/mock-da", features = ["native"] }
sov-modules-api = { path = ".", features = ["native"] }
sov-modules-core = { path = "../sov-modules-core", features = ["mocks"] }
sov-prover-storage-manager = { path = "../../full-node/sov-prover-storage-manager", features = ["test-utils"] }
tempfile = { workspace = true }

[features]
arbitrary = [
  "dep:arbitrary",
  "dep:proptest",
  "dep:proptest-derive",
  "proptest/default",
  "sov-state/arbitrary",
]
bench = [
  # "sov-zk-cycle-macros",
  "risc0-zkvm",
  "risc0-zkvm-platform",
]
default = ["macros"]
native = [
  "serde_json",
  "rand",
  "schemars",
  "serde",
  "ed25519-dalek/default",
  "ed25519-dalek/rand_core",
  "clap",
  "jsonrpsee",
  "macros",
  "sov-modules-core/native",
  "sov-modules-macros/native",
  "sov-state/native",
  "sov-prover-storage-manager",
]
macros = ["sov-modules-macros"]
serde = ["sov-modules-core/serde"]
