[package]
name = "sov-chain-state"
authors = { workspace = true }
description = "A Sovereign SDK module for storing a rollup's historical state"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = ["macros", "client-core", "server"], optional = true }

sov-modules-api = { path = "../../sov-modules-api", version = "0.3", default-features = false, features = [ "macros" ] }
sov-state = { path = "../../sov-state", version = "0.3" }

[dev-dependencies]
tempfile = { workspace = true }
sov-prover-storage-manager = { path = "../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }


[features]
default = ["native"]
native = ["serde_json", "jsonrpsee", "sov-state/native", "sov-modules-api/native"]
