[package]
name = "sov-zk-cycle-macros"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "cycle counting utils"

version = { workspace = true }
autotests = false
readme = "README.md"
resolver = "2"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/all_tests.rs"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
risc0-zkvm = { workspace = true, default-features = false, features = ["std"] }
risc0-zkvm-platform = { workspace = true }
sov-zk-cycle-macros = { path = "../../utils/zk-cycle-macros" }
sov-zk-cycle-utils = { path = "../../utils/zk-cycle-utils" }
trybuild = "1.0"

[features]
bench = []
