[package]
name = "sov-state"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Defines traits and types for state storage in the Sovereign SDK module system"

version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true, optional = true }
bcs = { workspace = true }
borsh = { workspace = true, features = ["rc", "bytes"] }
hex = { workspace = true }
jmt = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
serde = { workspace = true, features = ["rc"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
sov-db = { path = "../../full-node/db/sov-db", version = "0.3", optional = true }
sov-modules-core = { path = "../sov-modules-core", version = "0.3" }
sov-rollup-interface = { path = "../../rollup-interface", version = "0.3" }
thiserror = { workspace = true }

risc0-zkvm = { workspace = true, default-features = false, features = ["std"], optional = true }
risc0-zkvm-platform = { workspace = true, optional = true }
sov-zk-cycle-macros = { path = "../../utils/zk-cycle-macros", version = "0.3", optional = true }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }

[features]
arbitrary = [
  "dep:arbitrary",
  "dep:proptest",
  "dep:proptest-derive",
  "sov-modules-core/arbitrary",
]
bench = ["sov-zk-cycle-macros", "risc0-zkvm", "risc0-zkvm-platform"]
default = []
native = ["sov-db"]
