[package]
name = "citrea-risc0-bonsai-adapter"
authors = { workspace = true }
description = "An adapter allowing Citrea to connect with Bonsai"
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
risc0-zkvm = { workspace = true, default-features = false, features = ["std"] }
risc0-zkvm-platform = { workspace = true }
risc0-zkp = { workspace = true, optional = true }
risc0-circuit-rv32im = { workspace = true, optional = true }
serde = { workspace = true }
bytemuck = "1.13.1"
once_cell = { version = "1.19.0", optional = true }
parking_lot = { version = "0.12.3", optional = true }
sov-rollup-interface = { path = "../../rollup-interface" }
tracing = { workspace = true }
bonsai-sdk = "0.7.0"
hex = { workspace = true }

# we are going to use its guest
sov-risc0-adapter = { path = "../risc0", optional = true }


[features]
default = []
native = [
    "risc0-zkvm/prove",
    "dep:risc0-zkp",
    "dep:risc0-circuit-rv32im",
    "sov-risc0-adapter/native",
]
bench = ["once_cell", "parking_lot", "native"]

[[test]]
name = "native"
required-features = ["native"]
