[test-groups]
heavy-tests = { max-threads = 2 } # Limit to 2 tests concurrently running

[profile.default]
fail-fast = false

[[profile.default.overrides]]
filter = 'test(e2e::)'
test-group = 'heavy-tests'
threads-required = "num-cpus"
slow-timeout = { period = "360s" }
