sequencer_public_key = "204040e364c10f2bec9c1fe500a1cd4c247c89d650a01ed7e82caba867877c21"
include_tx_body = false

[da]
sender_address = "0000000000000000000000000000000000000000000000000000000000000000"

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "demo_data"

# We define the rollup's genesis to occur at block number `start_height`. The rollup will ignore
# any blocks before this height
[runner]
start_height = 0

[runner.rpc_config]
# the host and port to bind the rpc server for
bind_host = "0.0.0.0"
bind_port = 8545

[sequencer_client]
url = "http://0.0.0.0:8545"

[prover_service]
aggregated_proof_block_jump = 1
