min_soft_confirmations_per_commitment = 10
test_mode = false
[mempool_conf] # Mempool Configuration - https://github.com/ledgerwatch/erigon/wiki/Transaction-Pool-Design
pending_tx_limit = 100000
pending_tx_size = 200
queue_tx_limit = 100000
queue_tx_size = 200
base_fee_tx_limit = 100000
base_fee_tx_size = 200
max_account_slots = 16
[db_config]
db_host = "localhost"
db_port = 5432
db_user = "postgres"
db_password = "postgres"
db_name = "postgres"
