[package]
name = "sov-ledger-rpc"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "JSON-RPC server and client implementations for Sovereign SDK rollups"

version = { workspace = true }
publish = true
resolver = "2"

[dependencies]
# Common dependencies
# Client dependencies
# (None)
# Server dependencies
anyhow = { version = "1", optional = true }
futures = { version = "0.3", optional = true }
jsonrpsee = { workspace = true }
serde = "1"
sov-modules-api = { path = "../../module-system/sov-modules-api", features = ["native"], optional = true, version = "0.3" }
sov-rollup-interface = { path = "../../rollup-interface", features = ["native"], version = "0.3" }

[dev-dependencies]
serde_json = "1"
sov-db = { path = "../../full-node/db/sov-db" }
sov-ledger-rpc = { path = ".", features = ["client", "server"] }
tempfile = "3"
tokio = { workspace = true, features = ["full"] }

[features]
default = ["client", "server"]
server = ["anyhow", "futures", "jsonrpsee/server", "sov-modules-api"]
client = ["jsonrpsee/client", "jsonrpsee/macros"]
