[package]
name = "tracer"
version = "0.3.0"
edition = "2018"

[workspace]

[dependencies]
capstone = "0.11.0"
clap = { workspace = true }
goblin = "0.2"
indicatif = "0.17.6"
prettytable-rs = "^0.10"
regex = "1.5.4"
rustc-demangle = "0.1.18"
textwrap = "0.16.0"
