[package]
name = "sov-modules-stf-blueprint"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Defines a generic state transition function for use with the Sovereign SDK module system"

version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
hex = { workspace = true }
jmt = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }

jsonrpsee = { workspace = true, features = ["server"], optional = true }
risc0-zkvm = { workspace = true, default-features = false, features = ["std"], optional = true }
risc0-zkvm-platform = { workspace = true, optional = true }
sov-blob-storage = { path = "../module-implementations/sov-blob-storage" }
sov-chain-state = { path = "../module-implementations/sov-chain-state" }
sov-modules-api = { path = "../sov-modules-api", version = "0.3" }
sov-rollup-interface = { path = "../../rollup-interface", version = "0.3" }
sov-state = { path = "../sov-state", version = "0.3" }
sov-zk-cycle-macros = { path = "../../utils/zk-cycle-macros", version = "0.3", optional = true }
sov-zk-cycle-utils = { path = "../../utils/zk-cycle-utils", version = "0.3", optional = true }

[features]
bench = ["sov-zk-cycle-macros", "risc0-zkvm", "risc0-zkvm-platform"]
default = []
native = [
  "sov-state/native",
  "sov-modules-api/native",
  "jsonrpsee",
  "sov-chain-state/native",
  "sov-blob-storage/native",
]
