[package]
name = "demo-stf"
version = { workspace = true }
edition = { workspace = true }
resolver = "2"
authors = { workspace = true }
license = { workspace = true }
homepage = "sovereign.xyz"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = [
    "http-client",
    "server",
], optional = true }
tokio = { workspace = true, optional = true }
hex = { workspace = true }
tracing = { workspace = true }
reth-primitives = { workspace = true }
secp256k1 = { workspace = true }

sov-stf-runner = { path = "../../../sovereign-sdk/full-node/sov-stf-runner" }
sov-rollup-interface = { path = "../../../sovereign-sdk/rollup-interface" }
sov-sequencer-registry = { path = "../../../sovereign-sdk/module-system/module-implementations/sov-sequencer-registry" }
sov-bank = { path = "../../../sovereign-sdk/module-system/module-implementations/sov-bank" }

sov-modules-stf-blueprint = { path = "../../../sovereign-sdk/module-system/sov-modules-stf-blueprint" }
sov-value-setter = { path = "../../../sovereign-sdk/module-system/module-implementations/examples/sov-value-setter", default-features = false }
sov-accounts = { path = "../../../sovereign-sdk/module-system/module-implementations/sov-accounts", default-features = false }
sov-state = { path = "../../../sovereign-sdk/module-system/sov-state" }
sov-modules-api = { path = "../../../sovereign-sdk/module-system/sov-modules-api", default-features = false }
citrea-evm = { path = "../../../evm" }
soft-confirmation-rule-enforcer = { path = "../../../soft-confirmation-rule-enforcer" }


[dev-dependencies]
tempfile = { workspace = true }
rand = { workspace = true }
sov-prover-storage-manager = { path = "../../../sovereign-sdk/full-node/sov-prover-storage-manager", features = [
    "test-utils",
] }


[features]
default = ["native"]
native = [
    "sov-stf-runner/native",
    "sov-bank/native",
    "sov-accounts/native",
    "sov-sequencer-registry/native",
    "sov-value-setter/native",
    "sov-modules-api/native",
    "sov-rollup-interface/native",
    "sov-modules-stf-blueprint/native",
    "citrea-evm/native",
    "clap",
    "serde",
    "serde_json",
    "soft-confirmation-rule-enforcer/native",
    "jsonrpsee",
    "tokio",
]
serde = [
    "sov-bank/serde",
    "sov-sequencer-registry/serde",
    "sov-value-setter/serde",
    "sov-accounts/serde",
    "citrea-evm/serde",
    "soft-confirmation-rule-enforcer/serde",
]
