[package]
name = "demo-stf"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = "sovereign.xyz"
license = { workspace = true }
publish = false
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
clap = { workspace = true, optional = true }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["http-client", "server"], optional = true }
reth-primitives = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
tracing = { workspace = true }

sov-bank = { path = "../../../sovereign-sdk/module-system/module-implementations/sov-bank" }
sov-blob-storage = { path = "../../../sovereign-sdk/module-system/module-implementations/sov-blob-storage" }
sov-cli = { path = "../../../sovereign-sdk/module-system/sov-cli", optional = true }
sov-nft-module = { path = "../../../sovereign-sdk/module-system/module-implementations/sov-nft-module" }
sov-rollup-interface = { path = "../../../sovereign-sdk/rollup-interface" }
sov-sequencer-registry = { path = "../../../sovereign-sdk/module-system/module-implementations/sov-sequencer-registry" }
sov-soft-confirmations-kernel = { path = "../../../sovereign-sdk/module-system/sov-soft-confirmations-kernel" }
sov-stf-runner = { path = "../../../sovereign-sdk/full-node/sov-stf-runner" }

citrea-evm = { path = "../../../evm" }
soft-confirmation-rule-enforcer = { path = "../../../soft-confirmation-rule-enforcer" }
sov-accounts = { path = "../../../sovereign-sdk/module-system/module-implementations/sov-accounts" }
sov-chain-state = { path = "../../../sovereign-sdk/module-system/module-implementations/sov-chain-state" }
sov-mock-da = { path = "../../../sovereign-sdk/adapters/mock-da" }
sov-modules-api = { path = "../../../sovereign-sdk/module-system/sov-modules-api" }
sov-modules-stf-blueprint = { path = "../../../sovereign-sdk/module-system/sov-modules-stf-blueprint" }
sov-state = { path = "../../../sovereign-sdk/module-system/sov-state" }
sov-value-setter = { path = "../../../sovereign-sdk/module-system/module-implementations/examples/sov-value-setter" }

[dev-dependencies]
demo-stf = { path = ".", features = ["native"] }
rand = { workspace = true }
sov-data-generators = { path = "../../../sovereign-sdk/module-system/utils/sov-data-generators" }
sov-mock-zkvm = { path = "../../../sovereign-sdk/adapters/mock-zkvm" }
sov-prover-storage-manager = { path = "../../../sovereign-sdk/full-node/sov-prover-storage-manager", features = ["test-utils"] }
tempfile = { workspace = true }

[features]
default = []
offchain = ["sov-nft-module/offchain"]
native = [
  "sov-stf-runner/native",
  "sov-bank/native",
  "sov-nft-module/native",
  "sov-cli",
  "sov-accounts/native",
  "sov-sequencer-registry/native",
  "sov-blob-storage/native",
  "sov-chain-state/native",
  "sov-value-setter/native",
  "sov-modules-api/native",
  "sov-rollup-interface/native",
  "sov-mock-da/native",
  "sov-modules-stf-blueprint/native",
  "sov-soft-confirmations-kernel/native",
  "clap",
  "serde",
  "serde_json",
  "jsonrpsee",
  "tokio",
  "toml",
]
serde = [
  "sov-bank/serde",
  "sov-sequencer-registry/serde",
  "sov-blob-storage/serde",
  "sov-value-setter/serde",
  "sov-accounts/serde",
  "sov-nft-module/serde",
  "citrea-evm/serde",
  "soft-confirmation-rule-enforcer/serde",
]
