{
 "title": "Citrea Fullnode",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current L1 block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fullnode_current_l1_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current L2 block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fullnode_current_l2_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "L1 block scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "fullnode_scan_l1_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process l2 block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "fullnode_process_l2_block", "legendFormat": "__auto" }
   ]
  }
 ]
}