{
 "title": "New Light Client Prover Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "net_name", "label": "Net Name", "query": "test-net,dev-net,main-net" }
  ]
 },
 "panels": [
  {
   "title": "Current L1 Block",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "light_client_prover_current_l1_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proving Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "light_client_prover_proving_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scan L1 Block Duration",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "light_client_prover_current_l1_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "light_client_prover_scan_l1_block_duration_secs{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cycle Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "proving_session_cycle_count{job=\"citrea-light-prover\",net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rpc Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "light_client_prover_rpc_response_time{job=\"citrea-light-prover\",net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}