{
 "title": "Listen Mode Sequencer Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current L2 Block",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_current_l2_block{job=\"listen-mode-sequencer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current L1 Block",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_current_l1_block{job=\"listen-mode-sequencer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Process Durations Seconds By L2 Height",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sequencer_entire_block_production_duration_gauge{job=\"listen-mode-sequencer\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_current_l2_block{job=\"listen-mode-sequencer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Block Process Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sequencer_listen_mode_l1_block_process_duration_secs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions To Be Added Buffer Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sequencer_listen_mode_incoming_txs_to_be_added_buffer_size{job=\"listen-mode-sequencer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions To Be Removed Buffer Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sequencer_listen_mode_incoming_txs_to_be_removed_buffer_size{job=\"listen-mode-sequencer\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}