{
 "title": "Sequencer Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current L2 Block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sequencer_current_l2_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current L1 Block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sequencer_current_l1_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Num Of Deposit Txs In A Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(sequencer_deposit_data_mempool_txs_inc[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Of Txs In Mempool",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sequencer_mempool_txs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deposit Tx Call Duration",
   "type": "timeseries",
   "description": "The duration eth_call for deposit txs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sequencer_deposit_tx_call_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Base Fee Per Block Number",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "evm_base_fee_per_gas", "legendFormat": "__auto" },
    { "expr": "sequencer_last_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stacked Sequencer Block Production Flow",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "sequencer_current_l2_block", "legendFormat": "__auto" },
    {
     "expr": "sequencer_dry_run_preparation_time_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_dry_run_system_txs_time_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_dry_run_execution_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_begin_l2_block_time_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_encode_and_sign_sov_tx_time_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_apply_l2_block_txs_time_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_end_l2_block_time_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_finalize_l2_block_time_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_sign_l2_block_header_time_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_save_l2_block_time_gauge",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_maintain_mempool_gauge",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unaccepted Deposit Txs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_unaccepted_deposit_txs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deposit Tx Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "sequencer_deposit_tx_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bitcoin DA Queue Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "bitcoin_da_transaction_queue_processing_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Fee Rate Per Block",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "sequencer_current_l2_block", "legendFormat": "__auto" },
    { "expr": "sequencer_l1_fee_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of txs in deposit data mempool",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_deposit_data_mempool_txs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evm Gas Usage Per Block Num",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "evm_gas_usage", "legendFormat": "__auto" },
    { "expr": "sequencer_last_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "No Dry Run Block Production Time(secs) By Block Num",
   "type": "trend",
   "description": "Complete Block Production Time(secs) By Block Num",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "sequencer_last_block_number", "legendFormat": "__auto" },
    {
     "expr": "sequencer_block_production_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Count By Block Number",
   "type": "xychart",
   "description": "This does not work perfect in scenarios where there are over couple hundered missed DA blocks, and new l2 blocks are produced for every 10 L1 block instantly",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    { "expr": "sequencer_last_block_number", "legendFormat": "__auto" },
    { "expr": "sequencer_l2_block_tx_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Dry Run Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "expr": "sequencer_dry_run_execution", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Complete Produce L2 Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sequencer_block_production_execution",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rpc Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "expr": "sequencer_rpc_response_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Commitment Block Count By Index",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sequencer_currently_committing_index",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_commitment_blocks_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mine Sequencer Commitment Tx Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    { "expr": "type_4_mine_da_transaction", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of txs coming to the mempool in the last minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(sequencer_mempool_txs_inc[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Production Flow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dry Run Preparation Time",
     "type": "timeseries",
     "description": "Preparation done before running dry run txs function",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sequencer_dry_run_preparation_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dry Run System Txs Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "sequencer_dry_run_system_txs_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dry Run Time Per Tx Processing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      { "expr": "sequencer_dry_run_tx_time", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Begin L2 Block Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      { "expr": "sequencer_begin_l2_block_time", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Encode and Sign Sov Tx Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "sequencer_encode_and_sign_sov_tx_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Apply L2 Block Txs Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sequencer_apply_l2_block_txs_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "End L2 Block Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      { "expr": "sequencer_end_l2_block_time", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Finalize L2 Block Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "sequencer_finalize_l2_block_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sign L2 Block Header Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "sequencer_sign_l2_block_header_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Save L2 Block Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "targets": [
      { "expr": "sequencer_save_l2_block_time", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Maintain Mempool Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "sequencer_maintain_mempool_time",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}