[package]
name = "sov-sequencer"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "A simple implementation of a sequencer for Sovereign SDK rollups"

version = { workspace = true }
readme = "README.md"
resolver = "2"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
hex = { workspace = true }
jsonrpsee = { workspace = true, features = ["client", "server"] }
serde = { workspace = true, features = ["derive"] }
sov-modules-api = { path = "../../module-system/sov-modules-api", version = "0.3", features = ["native"] }
sov-rollup-interface = { path = "../../rollup-interface", version = "0.3" }
sov-state = { path = "../../module-system/sov-state", version = "0.3" }
tracing = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
rand = { workspace = true }
sov-db = { path = "../db/sov-db" }
sov-mock-da = { path = "../../adapters/mock-da", features = ["native"] }
sov-prover-storage-manager = { path = "../../full-node/sov-prover-storage-manager", features = ["test-utils"] }
sov-rollup-interface = { path = "../../rollup-interface", version = "0.3", features = ["native"] }
sov-schema-db = { path = "../db/sov-schema-db" }
sov-value-setter = { path = "../../module-system/module-implementations/examples/sov-value-setter", features = ["native"] }
tempfile = { workspace = true }
tokio = { workspace = true }
