[package]
name = "sov-blob-storage"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
description = "A Sovereign SDK module for holding blobs from Data Availability Layer"

resolver = "2"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }

sov-chain-state = { path = "../sov-chain-state", version = "0.3" }
sov-modules-api = { path = "../../sov-modules-api", version = "0.3" }
sov-sequencer-registry = { path = "../sov-sequencer-registry", version = "0.3" }
sov-state = { path = "../../sov-state", version = "0.3" }

clap = { workspace = true, optional = true }
jsonrpsee = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
jmt = { workspace = true }
sov-bank = { path = "../sov-bank" }
sov-blob-storage = { path = ".", features = ["native"] }
sov-mock-da = { path = "../../../adapters/mock-da", features = ["native"] }
sov-prover-storage-manager = { path = "../../../full-node/sov-prover-storage-manager", features = ["test-utils"] }
tempfile = { workspace = true }

[features]
default = []
native = [
  "jsonrpsee",
  "schemars",
  "serde",
  "serde_json",
  "sov-modules-api/native",
  "sov-state/native",
  "sov-sequencer-registry/native",
  "clap",
]
serde = ["dep:serde"]
