[da]
node_url = "http://localhost:38332"
node_username = "chainway"
node_password = "topsecret"
network = "regtest"
address = "bcrt1q02g8qhycr0v8cnflt86kksfe2sqhm486fdkx4l"
sequencer_da_private_key = "E9873D79C6D87DC0FB6A5778633389F4453213303DA61F20BD67FC233AA33262"
[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "demo_data"

# We define the rollup's genesis to occur at block number `start_height`. The rollup will ignore
# any blocks before this height
[runner]
start_height = 3

[runner.rpc_config]
# the host and port to bind the rpc server for
bind_host = "0.0.0.0"
bind_port = 12345

[sequencer_client]
start_height = 1
url = "http://0.0.0.0:12346"
