sequencer_public_key = "0000000000000000000000000000000000000000000000000000000000000000"
min_soft_confirmations_per_commitment = 1000

[da]
sender_address = "0000000000000000000000000000000000000000000000000000000000000000"

[storage]
# The path to the rollup's data directory. Paths that do not begin with `/` are interpreted as relative paths.
path = "demo_data"

# We define the rollup's genesis to occur at block number `start_height`. The rollup will ignore
# any blocks before this height
[runner]
start_height = 0

[runner.rpc_config]
# the host and port to bind the rpc server for
bind_host = "0.0.0.0"
bind_port = 12345

[sequencer_client]
# public ip of the sequencer
url = "http://159.89.214.47:12345"

[prover_service]
aggregated_proof_block_jump = 1
