[package]
name = "shared-backup-db"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
publish = false
readme = "README.md"
resolver = "2"

[dependencies]
hex = { workspace = true }
lazy_static = { version = "1.4.0", optional = true }
postgres = "0.19.7"
serde = { workspace = true }
tokio = { workspace = true }
tokio-postgres = "0.7.10"

[dev-dependencies]
shared-backup-db = { path = ".", features = ["test-utils"] }

[features]
default = []
test-utils = []
