[package]
name = "shared-backup-db"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
readme = "README.md"
publish = false
resolver = "2"

[dependencies]
postgres = "0.19.7"
tokio-postgres = "0.7.10"
serde = { workspace = true }
hex = { workspace = true }
tokio = { workspace = true }
lazy_static = { version = "1.4.0", optional = true }

[dev-dependencies]

[features]
default = []
