[package]
name = "citrea-network"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

version = { workspace = true }
publish = false
resolver = "2"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
libp2p = { workspace = true, features = ["tokio", "gossipsub", "noise", "tcp", "yamux", "quic", "macros", "mdns"] }
reth-tasks = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
yamux = { workspace = true }

citrea-common = { path = "../common" }
