{
 "title": "New Batch Prover Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "net_name", "label": "Net Name", "query": "test-net,dev-net,main-net" }
  ]
 },
 "panels": [
  {
   "title": "Current L2 and L1 Block",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "batch_prover_current_l2_block{net_name=\"$net_name\"}",
     "legendFormat": "L2 Block"
    },
    {
     "expr": "batch_prover_current_l1_block{net_name=\"$net_name\"}",
     "legendFormat": "L1 Block"
    }
   ]
  },
  {
   "title": "Process L2 Block Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "batch_prover_process_l2_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ongoing Proving jobs",
   "type": "timeseries",
   "description": "Ongoing Proof Count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "parallel_prover_service_ongoing_proving_jobs{service_name=\"citrea-prover\", net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proving Cycle Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "proving_session_cycle_count{service_name=\"citrea-prover\", net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Log Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "batch_prover_state_log_cache_size{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Complete Tx Mine Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "complete_mine_da_transaction{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Input Preparation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "batch_prover_total_input_preparation_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cumulative Witness Generation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "batch_prover_cumulative_witness_generation_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitcoin DA Transaction Queue Current Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "bitcoin_da_transaction_queue_size{net_name=\"$net_name\", job=\"citrea-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proof Count In Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "parallel_prover_service_proof_count_waiting_in_queue{net_name=\"$net_name\", job=\"citrea-prover\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offchain Log Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "batch_prover_offchain_log_cache_size{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunked Tx Mine Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "chunked_mine_da_transaction{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}