{
 "title": "Import From Prod New Full Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env_name",
    "label": "Env Name",
    "query": {
     "query": "label_values({net_name=\"$net_name\", job=\"citrea-full-node\"},env_name)"
    }
   },
   { "name": "net_name", "label": "Net Name", "query": "test-net,dev-net,main-net\n" }
  ]
 },
 "panels": [
  {
   "title": "Current L1 and L2 Block",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fullnode_current_l2_block{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "Current L2 Block"
    },
    {
     "expr": "fullnode_current_l1_block{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "Current L1 Block"
    }
   ]
  },
  {
   "title": "Highest Committed Index, L2 Height, Proven L2 Height",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fullnode_highest_committed_index{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "Highest Committed Index"
    },
    {
     "expr": "fullnode_highest_committed_l2_height{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "Highest Committed L2 Height"
    },
    {
     "expr": "fullnode_highest_proven_l2_height{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "Highest Proven L2 Height"
    }
   ]
  },
  {
   "title": "Per-second average rate of RPC requests over the last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(rpc_requests_total{net_name=\"$net_name\", env_name=\"$env_name\", job=\"citrea-full-node\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scan L1 Block Time By L1 Height",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "fullnode_current_l1_block{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fullnode_scan_l1_block_duration_secs{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rpc Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rpc_response_time_seconds{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process L2 Block Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "fullnode_process_l2_block{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Block Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "fullnode_l2_block_size{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Proof Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "fullnode_batch_proof_processing_time{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commitment Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "fullnode_sequencer_commitment_processing_time{net_name=\"$net_name\", env_name=\"$env_name\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}