{
 "title": "New Sequencer Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "net_name", "label": "Net Name", "query": "dev-net,test-net,main-net" }
  ]
 },
 "panels": [
  {
   "title": "Current L2 Block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_current_l2_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current L1 Block",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_current_l1_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num Of Deposit Txs In A Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(sequencer_deposit_data_mempool_txs_inc{net_name=\"$net_name\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Of Txs In Mempool",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transaction_pool_total_transactions{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-second average rate of RPC requests over the last 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(rpc_requests_total{net_name=\"$net_name\", job=\"citrea-sequencer\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rpc Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rpc_response_time_seconds{net_name=\"$net_name\", job=\"citrea-sequencer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stacked Sequencer Block Production Flow",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sequencer_current_l2_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_dry_run_preparation_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_dry_run_system_txs_duration_secs{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_dry_run_execution_gauge{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_begin_l2_block_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_encode_and_sign_sov_tx_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_apply_l2_block_txs_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_end_l2_block_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_finalize_l2_block_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_calculate_tx_merkle_root_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_sign_l2_block_header_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_save_l2_block_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_maintain_mempool_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_mempool_extract_bundle_state_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_mempool_canonical_notification_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Base Fee Per Block Number",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "evm_block_base_fee{net_name=\"$net_name\", env_name=\"core\", job=\"citrea-sequencer\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_current_l2_block{net_name=\"$net_name\", env_name=\"core\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evm Gas Usage Per Block Num",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "evm_block_gas_usage{net_name=\"$net_name\", job=\"citrea-sequencer\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_current_l2_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unaccepted Deposit Txs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_unaccepted_deposit_txs{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Complete Produce L2 Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sequencer_block_production_execution{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Dry Run Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sequencer_dry_run_execution{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Fee Rate Per Block",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sequencer_current_l2_block{net_name=\"$net_name\", job=\"citrea-sequencer\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_l1_fee_rate{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L1 Fee Failed Txs Count By Block Number",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sequencer_current_l2_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_l1_fee_failed_txs_count{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mine Sequencer Commitment Tx Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sequencer_commitment_mine_da_transaction{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of txs coming to the mempool in the last minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(transaction_pool_inserted_transactions{net_name=\"$net_name\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Count By Block Number",
   "type": "xychart",
   "description": "This does not work perfect in scenarios where there are over couple hundered missed DA blocks, and new l2 blocks are produced for every 10 L1 block instantly",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sequencer_current_l2_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_l2_block_tx_count{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitcoin DA Queue Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "bitcoin_da_transaction_queue_processing_time{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Commitment Data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_latest_sequencer_commitment_index{net_name=\"$net_name\"}",
     "legendFormat": "Latest Commitment Index"
    },
    {
     "expr": "sequencer_latest_sequencer_commitment_l2_start_height{net_name=\"$net_name\"}",
     "legendFormat": "Latest Commitment Start L2 Height"
    },
    {
     "expr": "sequencer_latest_sequencer_commitment_l2_end_height{net_name=\"$net_name\"}",
     "legendFormat": "Latest Commitment End L2 Height"
    }
   ]
  },
  {
   "title": "Number of txs in deposit data mempool",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_deposit_data_mempool_txs{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commitment Process Duration By Index",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sequencer_latest_sequencer_commitment_index{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_latest_sequencer_commitment_process_duration_secs{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No Dry Run Block Production Time(secs) By Block Num",
   "type": "trend",
   "description": "Complete Block Production Time(secs) By Block Num",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "sequencer_current_l2_block{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_no_dry_run_block_production_duration_secs{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deposit Tx Call Duration",
   "type": "timeseries",
   "description": "The duration eth_call for deposit txs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sequencer_deposit_tx_call_duration",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commitment Block Count By Index",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "sequencer_currently_committing_index{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sequencer_commitment_blocks_count{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deposit Tx Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "sequencer_deposit_tx_size{net_name=\"$net_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stacked Mempool Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "transaction_pool_pending_pool_size_bytes",
     "legendFormat": "Pending Pool Size"
    },
    {
     "expr": "transaction_pool_basefee_pool_size_bytes",
     "legendFormat": "Basefee Pool Size"
    },
    {
     "expr": "transaction_pool_queued_pool_size_bytes",
     "legendFormat": "Queued Pool Size"
    }
   ]
  },
  {
   "title": "Stacked Mempool Transaction Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "transaction_pool_pending_pool_transactions",
     "legendFormat": "Pending Pool"
    },
    {
     "expr": "transaction_pool_basefee_pool_transactions",
     "legendFormat": "Basefee Pool"
    },
    {
     "expr": "transaction_pool_queued_pool_transactions",
     "legendFormat": "Queued Pool"
    }
   ]
  },
  {
   "title": "Mempool Transaction Flow (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(transaction_pool_inserted_transactions[1m])",
     "legendFormat": "Inserted Transactions/sec"
    },
    {
     "expr": "rate(transaction_pool_removed_transactions[1m])",
     "legendFormat": "Removed Transactions/sec"
    }
   ]
  }
 ]
}